### PR TITLE
Add xmc4300 support

### PR DESCRIPTION
**Pull request by sittner**
Added support for Infineon's XMC4300 (and potentially XMC4800).
Including adapted demo application and EEPROM emulation (separated ESC and HAL layer).

Removed ALevents from every HAL ESC_read/ESC_write call and use ESCvar.ALevent in HAL. Don't know if that is OK, but seems more effective and logical to me.

### CODE REVIEW

**Comment by nakarlsson** [comment]
I'm reviewing it.

**Comment by nakarlsson** [comment]
Can you split the Pull Request in XMC support & Alevent removal.

**Comment by sittner** [comment]
OK. I have created a new branch "Cleanup hal alevent" and rebased this branch to that.

**Comment by nakarlsson** [comment]
I've tried porting it to XMC4800 but fail to go to SAFEOP, before investigating further I'd like to ask if you've run CTT and can go to OP?
Also to constribute we need a signed CLA.

**Comment by sittner** [comment]
The CTT run is still pending. I'm using this code the last weeks for implementing a measurement device and it runs fine (at least with the IgH master). I will do the CTT on the next few days and will try to fix potential issues.

What kind of CLA it will be. I've never seen this in conjunction with an GPL project before. Please send it to me and I will verify if we are OK with it (sascha dot ittner at modusoft dot de). We are also member of the ETG.

**Comment by nakarlsson** [comment]
My XMC4800 port now pass CTT, we can re-use the device define to do the proper adoptions, I'll do that later. However, the XMCLib you mention is not available anymore. Perhaps we should add a more generic link where to find the lib. Perhaps even store a copy for safe keeping.

CLA:
https://github.com/OpenEtherCATsociety/OpenEtherCATsociety.github.io/blob/master/cla/cla_soem_soes.pdf

**Comment by nakarlsson** [comment]
Do you want to proceed?

**Comment by sittner** [comment]
Yes, certainly, but very busy at the moment and I've forgotten to scan the CLA as I was in the office. I will send it to you next week.

**Comment by nakarlsson** [comment]
CLA recived

**Pull request merged**
